---
  - name: install prereqs
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - unzip
      - gcc
      - java-1.8.0-openjdk

  - name: create the tuxedo users group
    group:
      name: "{{tuxedo_user_group}}"

  - name: add tuxedo user
    user:
      name: "{{tuxedo_user}}"
      createhome: yes
      home: "{{tuxedo_user_home}}"
      group: "{{tuxedo_user_group}}"
      append: yes

  - name: copy over the install media
    get_url:
      url: "{{tuxedo_url}}"
      dest: "{{tuxedo_user_home}}"
      group: "{{tuxedo_user_group}}"
      owner: "{{tuxedo_user}}"
      mode: 0664
    register: tuxedo_zipfile

  - name: unzip
    unarchive: 
      src: "{{ tuxedo_zipfile.dest }}"
      dest: "{{tuxedo_user_home}}"
      remote_src: yes
      creates: "{{tuxedo_user_home}}/Disk1/install/runInstaller.sh"
    become: yes
    become_user: "{{tuxedo_user}}"

  - name: create the oracle inventory file
    template:
      src: templates/etc_oraInst.loc.j2
      dest: /etc/oraInst.loc
      group: "{{tuxedo_user_group}}"
      owner: "{{tuxedo_user}}"
      mode: 0664

  - name: create the installer.properties file
    template:
      src: templates/installer.properties
      dest: "{{tuxedo_user_home}}"
      group: "{{tuxedo_user_group}}"
      owner: "{{tuxedo_user}}"
      mode: 0664

  - name: run the installer
    shell: export JAVA_HOME=/usr/lib/jvm/jre && {{tuxedo_user_home}}/Disk1/install/runInstaller.sh -responseFile ~/installer.properties -silent -waitforcompletion
    args:
      creates: "{{tuxedo_user_home}}/tux_1/"
    become: yes
    become_user: "{{tuxedo_user}}"

